name: Mac OS X check

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-no-steamworks:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install-dependencies
      run: brew install gcc@11 cmake qt@5 openssl@1.1
    - name: make build directory
      run: mkdir build && cd build
    - name: cmake
      run: cd build && cmake .. -DCPACK_GENERATOR=DragNDrop -DCMAKE_PREFIX_PATH='/usr/local;/opt/homebrew;/opt/homebrew/opt/qt@5;/opt/homebrew/opt/openssl@1.1' -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror -static-libgcc" -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11 -DRUN_TESTS=ON -DDEVELOPER_MODE=ON -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12
    - name: build
      run: cd build && make -j$(sysctl -n hw.ncpu)
    - name: run tests
      run: cd build && ctest --output-on-failure
